version: '3'
services:
  devcontainer:
  
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile                                                                                                              
      args:
        HOST_USER_UID: 1000
        HOST_USER_GID: 1000
    network_mode: host
    environment:
      - DISPLAY=$DISPLAY

    volumes:
      - ..:/workspace
      - ~/.gitconfig:/home/containeruser/.gitconfig
      - ~/.ssh:/home/containeruser/.ssh
      - "$HOME/.Xauthority:/root/.Xauthority:rw"

    command: sleep infinity 
